name: Sync Stable Diffusion
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout down
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pull Original Code
        run: |
          git config --global user.name "ivanovich1202-beep"
          git config --global user.email "ivanovich1202@gmail.com"
          git remote add upstream https://github.com
          git fetch upstream
          git checkout -B main
          git merge upstream/master --allow-unrelated-histories -m "Inyeccion Completa de Stable Diffusion"
          git push origin main --force
